//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.VideoRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string streetAddress { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> zip { get; set; }
        public string phone { get; set; }
        public string userName { get; set; }
        public string llv_password { get; set; }
        public string salt { get; set; }
        public Nullable<bool> manager { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
