//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.VideoRental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LacklusterEntities : DbContext
    {
        public LacklusterEntities()
            : base("name=LacklusterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
<<<<<<< HEAD
=======
        public virtual DbSet<dvd> dvds { get; set; }
>>>>>>> 09f44574a441a377f57292ab13b587dd8171e463
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<rental> rentals { get; set; }
        public virtual DbSet<video> videos { get; set; }
    }
}
