//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.VideoRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class rental
    {
        public int rentalID { get; set; }
        public int custID { get; set; }
        public int videoID { get; set; }
        public int empID { get; set; }
        public Nullable<System.DateTime> dayRented { get; set; }
        public Nullable<System.DateTime> dayDue { get; set; }
        public Nullable<bool> returned { get; set; }
    }
}
