//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NV.VideoRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public int videoID { get; set; }
        public string title { get; set; }
        public string studio { get; set; }
        public Nullable<System.DateTime> released { get; set; }
        public string status { get; set; }
        public string sound { get; set; }
        public string versions { get; set; }
        public Nullable<decimal> price { get; set; }
        public string rating { get; set; }
        public string year { get; set; }
        public string genre { get; set; }
        public string aspect { get; set; }
        public string UPC { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public Nullable<bool> active { get; set; }
<<<<<<< HEAD
        public bool rented { get; set; }
=======
>>>>>>> 09f44574a441a377f57292ab13b587dd8171e463
    }
}
